### PR TITLE
added sample apps, added more descriptions

### PR DESCRIPTION
**Pull request by GiacomoLaw**

### CODE REVIEW

**Comment by carmichaelalonso** [comment]
Technically this is a sample project - the API server is run off of each Infinite Flight instance. Could be useful to include a link to show a few examples, including this and LiveFlight Connect (macOS version has Swift wrapper)

**Comment by GiacomoLaw** [comment]
@carmichaelalonso Thats a nice idea. Liveflight Connect has the networking in it, right?

**Comment by GiacomoLaw** [comment]
I did as you recommended @carmichaelalonso :)

**Comment by GiacomoLaw** [comment]
Sorry about this one: f0a912fa3138177867b13fde685f0871caa55eb8

I didn't realize that GitHub markdown did not support commenting 😞

**Comment by carmichaelalonso** [comment]
Taxi lights is likely an internal thing. Whilst it has no "visible" effect, the command exists.

**Pull request merged**
